### ISSUE TITLE
Detected: Backdoor:Win32/Bladabindi!ml

### ISSUE THREAD

**Issue by djayor** [FrostySo/Ps4-Pkg-Sender#10]
The program is detected as a threat by windows security:
Backdoor:Win32/Bladabindi!ml
Is possible in future releases try to change the signature to avoid it?

**Comment by FrostySo** [comment]
I've changed it. However, It is still detecting it as a virus.

None of them seem to be marked as backdoors though.

https://www.virustotal.com/gui/file/ea7397fb4d696868ae431982239359f6586fb96acae81c3a1b9c96d83df122db/detection

See if that helps.
