### ISSUE TITLE
Unable to send from another server ip

### ISSUE THREAD

**Issue by dobber81** [FrostySo/Ps4-Pkg-Sender#11]
I use my nas as http server for send pkg files to my ps4.
nas: 10.0.0.10
computer: 10.0.0.16
ps4: 10.0.0.30

In the old PS4 Package Sender v1.2 I was able to set server as 10.0.0.10 and drop files from the nas in the app, click send and the ps4 would pull the pkg from my nas, not using my computer as a middleman. I could even turn off my computer once the transfer was started.

Is it possible to set another ip than the computer running this app?

**Comment by FrostySo** [comment]
I'm not sure how you were able to do that last time. I don't think I had anything changed to do with the server IP code.

The sender initializes a new instance of the nodejs http server on the desired IP, then sends it. 

If the NAS is just completely used for storage, then it should be able to pick it out using the filepath. But I do remember, if the path of the file was outside of the C drive, the nodejs server would fail for whatever reason. In the future, I might consider moving into an inbuilt http server, that doesn't require any pre-requisites on your end, for better control. 

But if you believe it will help, I can add an option to manually add IP addresses. Which will save to a file and load it.

**Comment by dobber81** [comment]
I'm sorry. I just noticed I was using the 1.2 app from Modded_Warfare. I thought this was an updated version of that app. I do like your gui better. So if the function I requested was to be implemented, I would rather stay with this app.

**Comment by FrostySo** [comment]
Hi again. 

I have added it in and pushed the commits.

Give this a go and let me know how it goes. 

Please do note this though. File renaming is not supported with network drives. So you will have to manually rename them if it fails. It will tell you if it fails. 

Other than that, this should be what you need.
[Release.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/6177121/Release.zip)

**Comment by dobber81** [comment]
Thank you! I just tried it and it works!

**Comment by FrostySo** [comment]
> Thank you! I just tried it and it works!

Great! I will be closing this now. Feel free to reopen it if any issues arise, with this matter.
