### ISSUE TITLE
HTTP 500 Error while processing queue

### ISSUE THREAD

**Issue by pratikrao2195** [FrostySo/Ps4-Pkg-Sender#16]
I own PS4 Pro japan imported currently on 7.55 firmware using latest goldhen 1.1 payload and already used disable update and history blocker payload at first attempt of jailbreak, so I've tried version 1.06 nodejsfix of package sender LAN method to send pkg files via laptop but no luck I've always got HTTP 500 error both of server and PS4 IP are correct.

I've used latest nodejs version plus latest http-server plugin I've tried everything first I've disabled windows firewall and turned off any antivirus of windows then I've used another HDD volume and also used pkg from HDD volume's root directory but both of them never worked I always got HTTP 500 error

**Comment by FrostySo** [comment]
This will be very hard to debug without knowing a few things. 

1. What pkg is it? Mind giving me a name + hash? (md5 or sha256/512 is fine). 
2. Are you using Wifi or Ethernet?
3. Have you tried any other pkg file? I do know that some theme's/dlc's (which are small files) refuse to send. This is not an issue with the sender, but rather the remote package installer. 
4. Have you tried another pkg sender? 
5. Have you tried it with mira? (Just as a test)
6. If you type `ipconfig` on cmd, will the ip of your ps4 be listed there? You can check by going on your ps4 -> network settings -> network status or info (I forgot what it's called). Then you just see if the local ip matches the ones in CMD. You should also try visit a site, just to ensure the internet connection is working. If on ethernet, your pc should be providing the internet. If on wifi, you should be on the same gateway (same DHCP server). 

We just need to go through all these steps so we can figure out your issue.  You've followed the modded warefare tutorial right? Just gotta make sure everything on your end is correct, so we can start eliminating possibilities.

**Comment by pratikrao2195** [comment]
> This will be very hard to debug without knowing a few things.
> 
> 1. What pkg is it? Mind giving me a name + hash? (md5 or sha256/512 is fine).
> 2. Are you using Wifi or Ethernet?
> 3. Have you tried any other pkg file? I do know that some theme's/dlc's (which are small files) refuse to send. This is not an issue with the sender, but rather the remote package installer.
> 4. Have you tried another pkg sender?
> 5. Have you tried it with mira? (Just as a test)
> 6. If you type `ipconfig` on cmd, will the ip of your ps4 be listed there? You can check by going on your ps4 -> network settings -> network status or info (I forgot what it's called). Then you just see if the local ip matches the ones in CMD. You should also try visit a site, just to ensure the internet connection is working. If on ethernet, your pc should be providing the internet. If on wifi, you should be on the same gateway (same DHCP server).
> 
> We just need to go through all these steps so we can figure out your issue. You've followed the modded warfare tutorial (https://www.youtube.com/watch?v=v04zI5SD07k) right? Just gotta make sure everything on your end is correct, so we can start eliminating possibilities.

1. check attached image for pkg viewer screenshot
2. Ethernet
3. Yes I tried other game's main game pkg files too and I have not used updates or theme pkg file
4. I've tried moddedwarfare's package sender 1.2 it also haven't worked and also tried benjaminfaal's package sender 0.0.7 this one worked
5. I've tried with mira, goldhen 1.0, goldhen 1.1b7 and goldhen 1.1 all of them
6. Yes it showed there in cmd I also ping on it too so its giving successful response on cmd, I already followed this guide https://www.youtube.com/watch?v=wL6LHg7IEsM for network setup plus also installed http-server using mentioned command too and both laptop and PS4 Pro's IP showing correctly because current configuration works with benjaminfaal's package sender 0.0.7 but it doesn't support queue based pkg transfer and also after sending 2-3 big games pkg files it often freezes transfer so I've to restart transfer again from scratch

![image](https://user-images.githubusercontent.com/30404333/120844316-d2f07780-c58c-11eb-9443-41ed41871374.png)

**Comment by FrostySo** [comment]
So if benjamin's one works, then there's an issue with the config. 

I believe benjamin uses peer to peer. But this gives me an indication that it might be an issue with nodejs possibly not working correctly if it doesn't work for mine or modded warfares. 

https://youtu.be/_w0wfMEAH3I?t=264 Follow this tut here, and download the manual files. Do it and then show me what the cmd's show as an output please. My bet is it will not output anything, meaning it is a nodejs (or a connection problem between the 2 devices). 

I know this gets confusing. But we must keep going until we reach a solution that works for you. 

With benjamin's one, I'd assume that game sends fine?

**Comment by pratikrao2195** [comment]
I've followed these steps and getting this error
![image](https://user-images.githubusercontent.com/30404333/120982976-e40cd480-c796-11eb-9bff-9d86f2a0f871.png)

**Comment by FrostySo** [comment]
> I've followed these steps and getting this error
> ![image](https://user-images.githubusercontent.com/30404333/120982976-e40cd480-c796-11eb-9bff-9d86f2a0f871.png)

Wow he would replace the original CMD's with others. Here, use this and follow the steps in the tut. 

But the odds are, it isn't getting a connection to your ps4, from your pc.  However, now I see there's "[downloadgamesps3.com]-"

Special characters can ruin the pkg sender. Remove that whole beginning including the - so it should be named like Yakuza.Like....DUPLEX.pkg instead. If it works, then I guess there's your problem. 




[pkg sender.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/6607600/pkg.sender.zip)

**Comment by pratikrao2195** [comment]
> > I've followed these steps and getting this error
> > ![image](https://user-images.githubusercontent.com/30404333/120982976-e40cd480-c796-11eb-9bff-9d86f2a0f871.png)
> 
> Wow he would replace the original CMD's with others. Here, use this and follow the steps in the tut.
> 
> But the odds are, it isn't getting a connection to your ps4, from your pc. However, now I see there's "[downloadgamesps3.com]-"
> 
> Special characters can ruin the pkg sender. Remove that whole beginning including the - so it should be named like Yakuza.Like....DUPLEX.pkg instead. If it works, then I guess there's your problem.
> 
> [pkg sender.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/6607600/pkg.sender.zip)

I've used this pkg sender now so I've to make changes to PS4 IP address and also changed server's IP's port to 8081 and after that I've drag n dropped my pkg file after removing all special characters and then this one is also working but it seems to be slow in speed though I'm using LAN cable check this screenshot
![image](https://user-images.githubusercontent.com/30404333/121062573-dd0bb380-c7e2-11eb-80c9-1705debab95c.png)

**Comment by FrostySo** [comment]
Now try it again with my tool and it should work. They are both pretty much using the same thing. 

As for speed, that's up to you. Your hard drive speed + your ethernet cable quality + your ethernet cable port takes a huge part into the speed. 

Ethernet cable - needs to handle a certain bandwith
Ethernet port - needs to handle that certain transmission bandwith
Hard drive - your hdd can be slow. Speed impacts it a lot. Your RPM can impact it, the amount of files left on hard drive, the amount of abuse the hard drive has had etc.

**Comment by pratikrao2195** [comment]
I've used 1.06 nodejsfix again check this screenshot but its not working
settings.json as follows:
{
  "ServerIP": "192.168.137.1",
  "Ps4IP": "192.168.137.126",
  "RecursiveSearch": false,
  "ProgressCheckDelay": 10
}
![image](https://user-images.githubusercontent.com/30404333/121065381-53f67b80-c7e6-11eb-84ab-e731abb9a8b7.png)

**Comment by Pratik-Buyogo** [comment]
> I've used 1.06 nodejsfix again check this screenshot but its not working
> settings.json as follows:
> {
> "ServerIP": "192.168.137.1",
> "Ps4IP": "192.168.137.126",
> "RecursiveSearch": false,
> "ProgressCheckDelay": 10
> }
> ![image](https://user-images.githubusercontent.com/30404333/121065381-53f67b80-c7e6-11eb-84ab-e731abb9a8b7.png)

I found the problem its with port number actually I'm a software developer too so I've already installed apache tomcat on 8080 so I've just changed its port number so now pkg sender is running fine I've also looked at source code and I saw that you're using default 8080 port and also check its available if it isn't then you use a random port I think there should be a problem with that code of yours that's why it won't worked earlier when my tomcat already have 8080 any way I think its faster then benjaminfaal's pkg sender I've sent 45gb pkg file in 12 minutes.

what I suggest that you should check that random port generation code again to verify that its working with http-server or not and It would be better if you could give an input field for port number to enter for server IP's port so it give more ease to use.

**Comment by pratikrao2195** [comment]
> I've used 1.06 nodejsfix again check this screenshot but its not working
> settings.json as follows:
> {
> "ServerIP": "192.168.137.1",
> "Ps4IP": "192.168.137.126",
> "RecursiveSearch": false,
> "ProgressCheckDelay": 10
> }
> ![image](https://user-images.githubusercontent.com/30404333/121065381-53f67b80-c7e6-11eb-84ab-e731abb9a8b7.png)

I found the problem its with port number actually I'm a software developer too so I've already installed apache tomcat on 8080 so I've just changed its port number so now pkg sender is running fine I've also looked at source code and I saw that you're using default 8080 port and also check its available if it isn't then you use a random port I think there should be a problem with that code of yours that's why it won't worked earlier when my tomcat already have 8080 any way I think its faster then benjaminfaal's pkg sender I've sent 45gb pkg file in 12 minutes.

what I suggest that you should check that random port generation code again to verify that its working with http-server or not and It would be better if you could give an input field for port number to enter for server IP's port so it give more ease to use.

**Comment by FrostySo** [comment]
> > I've used 1.06 nodejsfix again check this screenshot but its not working
> > settings.json as follows:
> > {
> > "ServerIP": "192.168.137.1",
> > "Ps4IP": "192.168.137.126",
> > "RecursiveSearch": false,
> > "ProgressCheckDelay": 10
> > }
> > ![image](https://user-images.githubusercontent.com/30404333/121065381-53f67b80-c7e6-11eb-84ab-e731abb9a8b7.png)
> 
> I found the problem its with port number actually I'm a software developer too so I've already installed apache tomcat on 8080 so I've just changed its port number so now pkg sender is running fine I've also looked at source code and I saw that you're using default 8080 port and also check its available if it isn't then you use a random port I think there should be a problem with that code of yours that's why it won't worked earlier when my tomcat already have 8080 any way I think its faster then benjaminfaal's pkg sender I've sent 45gb pkg file in 12 minutes.
> 
> what I suggest that you should check that random port generation code again to verify that its working with http-server or not and It would be better if you could give an input field for port number to enter for server IP's port so it give more ease to use.

Great! Glad you got it sorted. I didn't even know that the port could've been an issue, as I tested that function many times before releasing it. I even kept the ports open intentionally. The fact you were able to initiate the server means the port should have been changed. Cause if it was, it would've given an error `"EADDRINUSE"` which then the program would have picked up, and told you about. I made the assumption that the random ports it picks would be free (since they weren't used anywhere on the known ports section).  I could easily add a while loop to ensure it checks the new port before it proceeds. Debugging this is pretty difficult in this situation, since I tested it multiple times with many different people. Worked good for everyone, but clearly staged tests don't give you the unexpected results  that the real world does 😁

Does Tomcat (I'd assume TCP here) run on tcp or udp? Cause I only check tcp connections, not udp since 8080 is most commonly on tcp. I'll do some thinking and see what I can do to avoid it. 

If you could, could you do `netstat -a` and tell me what it says for your tomcat? Most likely would say TCP 8080 LISTENING, but I'd just like to double check.

**Comment by pratikrao2195** [comment]
> > > I've used 1.06 nodejsfix again check this screenshot but its not working
> > > settings.json as follows:
> > > {
> > > "ServerIP": "192.168.137.1",
> > > "Ps4IP": "192.168.137.126",
> > > "RecursiveSearch": false,
> > > "ProgressCheckDelay": 10
> > > }
> > > ![image](https://user-images.githubusercontent.com/30404333/121065381-53f67b80-c7e6-11eb-84ab-e731abb9a8b7.png)
> > 
> > 
> > I found the problem its with port number actually I'm a software developer too so I've already installed apache tomcat on 8080 so I've just changed its port number so now pkg sender is running fine I've also looked at source code and I saw that you're using default 8080 port and also check its available if it isn't then you use a random port I think there should be a problem with that code of yours that's why it won't worked earlier when my tomcat already have 8080 any way I think its faster then benjaminfaal's pkg sender I've sent 45gb pkg file in 12 minutes.
> > what I suggest that you should check that random port generation code again to verify that its working with http-server or not and It would be better if you could give an input field for port number to enter for server IP's port so it give more ease to use.
> 
> Great! Glad you got it sorted. I didn't even know that the port could've been an issue, as I tested that function many times before releasing it. I even kept the ports open intentionally. The fact you were able to initiate the server means the port should have been changed. Cause if it wasn't, it would've given an error `"EADDRINUSE"` which then the program would have picked up, and told you about it. I made the assumption that the random ports it picks would be free (since they weren't used anywhere on the known ports section). I could easily add a while loop to ensure it checks the new port before it proceeds. Debugging this is pretty difficult in this situation, since I tested it multiple times with many different people. Worked good for everyone, but clearly staged tests don't give you the unexpected results that the real world does 😁
> 
> Does Tomcat (I'd assume TCP here) run on tcp or udp? Cause I only check tcp connections, not udp since 8080 is most commonly on tcp. I'll do some thinking and see what I can do to avoid it.
> 
> If you could, could you do `netstat -a` and tell me what it says for your tomcat? Most likely would say TCP 8080 LISTENING, but I'd just like to double check.

It gives following output

Microsoft Windows [Version 10.0.19043.1023]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Pratik>netstat -a

Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:135            LAPTOP-450O6GAV:0      LISTENING
  TCP    0.0.0.0:445            LAPTOP-450O6GAV:0      LISTENING
  TCP    0.0.0.0:2869           LAPTOP-450O6GAV:0      LISTENING
  TCP    0.0.0.0:3306           LAPTOP-450O6GAV:0      LISTENING
  TCP    0.0.0.0:5040           LAPTOP-450O6GAV:0      LISTENING
  TCP    0.0.0.0:7070           LAPTOP-450O6GAV:0      LISTENING
  TCP    0.0.0.0:8084           LAPTOP-450O6GAV:0      LISTENING
  TCP    0.0.0.0:33060          LAPTOP-450O6GAV:0      LISTENING
  TCP    0.0.0.0:36471          LAPTOP-450O6GAV:0      LISTENING
  TCP    0.0.0.0:49664          LAPTOP-450O6GAV:0      LISTENING
  TCP    0.0.0.0:49665          LAPTOP-450O6GAV:0      LISTENING
  TCP    0.0.0.0:49666          LAPTOP-450O6GAV:0      LISTENING
  TCP    0.0.0.0:49667          LAPTOP-450O6GAV:0      LISTENING
  TCP    0.0.0.0:49668          LAPTOP-450O6GAV:0      LISTENING
  TCP    0.0.0.0:49670          LAPTOP-450O6GAV:0      LISTENING
  TCP    0.0.0.0:49674          LAPTOP-450O6GAV:0      LISTENING
  TCP    127.0.0.1:1001         LAPTOP-450O6GAV:0      LISTENING
  TCP    127.0.0.1:6341         LAPTOP-450O6GAV:0      LISTENING
  TCP    127.0.0.1:6342         LAPTOP-450O6GAV:0      LISTENING
  TCP    127.0.0.1:28385        LAPTOP-450O6GAV:0      LISTENING
  TCP    127.0.0.1:28390        LAPTOP-450O6GAV:0      LISTENING
  TCP    127.0.0.1:49350        LAPTOP-450O6GAV:0      LISTENING
  TCP    127.0.0.1:49678        license:49679          ESTABLISHED
  TCP    127.0.0.1:49679        license:49678          ESTABLISHED
  TCP    127.0.0.1:49686        license:49687          ESTABLISHED
  TCP    127.0.0.1:49687        license:49686          ESTABLISHED
  TCP    127.0.0.1:49713        license:49714          ESTABLISHED
  TCP    127.0.0.1:49714        license:49713          ESTABLISHED
  TCP    127.0.0.1:50050        license:50052          ESTABLISHED
  TCP    127.0.0.1:50052        license:50050          ESTABLISHED
  TCP    127.0.0.1:50054        license:50056          ESTABLISHED
  TCP    127.0.0.1:50056        license:50054          ESTABLISHED
  TCP    127.0.0.1:50058        license:50060          ESTABLISHED
  TCP    127.0.0.1:50060        license:50058          ESTABLISHED
  TCP    127.0.0.1:51179        license:51180          ESTABLISHED
  TCP    127.0.0.1:51180        license:51179          ESTABLISHED
  TCP    127.0.0.1:53372        license:53373          ESTABLISHED
  TCP    127.0.0.1:53373        license:53372          ESTABLISHED
  TCP    127.0.0.1:53441        license:53439          TIME_WAIT
  TCP    127.0.0.1:53442        license:53440          TIME_WAIT
  TCP    127.0.0.1:53460        license:53461          ESTABLISHED
  TCP    127.0.0.1:53461        license:53460          ESTABLISHED
  TCP    127.0.0.1:53472        license:53471          TIME_WAIT
  TCP    127.0.0.1:55476        license:49350          TIME_WAIT
  TCP    127.0.0.1:55483        license:49350          TIME_WAIT
  TCP    127.0.0.1:55492        license:49350          TIME_WAIT
  TCP    127.0.0.1:56440        license:49350          TIME_WAIT
  TCP    127.0.0.1:56441        license:49350          TIME_WAIT
  TCP    127.0.0.1:57586        LAPTOP-450O6GAV:0      LISTENING
  TCP    127.0.0.1:61026        license:49350          TIME_WAIT
  TCP    127.0.0.1:61027        license:49350          TIME_WAIT
  TCP    127.0.0.1:61031        license:49350          TIME_WAIT
  TCP    127.0.0.1:61045        license:49350          TIME_WAIT
  TCP    127.0.0.1:61047        license:49350          TIME_WAIT
  TCP    127.0.0.1:61048        license:49350          TIME_WAIT
  TCP    127.0.0.1:61050        license:49350          TIME_WAIT
  TCP    127.0.0.1:64282        license:64283          ESTABLISHED
  TCP    127.0.0.1:64283        license:64282          ESTABLISHED
  TCP    127.0.0.1:64284        license:64285          ESTABLISHED
  TCP    127.0.0.1:64285        license:64284          ESTABLISHED
  TCP    127.0.0.1:64288        license:64291          ESTABLISHED
  TCP    127.0.0.1:64291        license:64288          ESTABLISHED
  TCP    192.168.0.105:139      LAPTOP-450O6GAV:0      LISTENING
  TCP    192.168.0.105:49718    bom12s12-in-f10:https  ESTABLISHED
  TCP    192.168.0.105:49737    c-71-227-18-58:5544    ESTABLISHED
  TCP    192.168.0.105:49783    199.232.192.64:https   ESTABLISHED
  TCP    192.168.0.105:49834    104.16.160.13:https    ESTABLISHED
  TCP    192.168.0.105:49845    kul01s09-in-f67:https  ESTABLISHED
  TCP    192.168.0.105:50964    bt2:https              ESTABLISHED
  TCP    192.168.0.105:51028    1:https                TIME_WAIT
  TCP    192.168.0.105:51160    ec2-13-233-76-15:https  ESTABLISHED
  TCP    192.168.0.105:51261    bom07s27-in-f3:https   ESTABLISHED
  TCP    192.168.0.105:51386    bom07s20-in-f14:https  ESTABLISHED
  TCP    192.168.0.105:53137    104.18.98.194:https    TIME_WAIT
  TCP    192.168.0.105:53297    cdn-185-199-108-133:https  ESTABLISHED
  TCP    192.168.0.105:53457    bom07s18-in-f10:https  ESTABLISHED
  TCP    192.168.0.105:53464    20.198.162.76:https    ESTABLISHED
  TCP    192.168.0.105:53465    bom05s11-in-f10:https  ESTABLISHED
  TCP    192.168.0.105:53476    relay-f8763563:http    ESTABLISHED
  TCP    192.168.0.105:53754    bom07s15-in-f22:https  ESTABLISHED

**Comment by FrostySo** [comment]
Is netstat running at this point? I don't see port 8080 anywhere here, when it should be. 

try `netstat -na | find "8080"` and let me know if it shows nothing or something. If nothing, then that might be why it bugged out. The port was technically not in use.

**Comment by pratikrao2195** [comment]
its giving this now

C:\Users\Pratik>netstat -na | find "8080"
  TCP    0.0.0.0:8080           0.0.0.0:0              LISTENING
  TCP    [::]:8080              [::]:0                 LISTENING
  TCP    [::1]:8080             [::1]:52533            ESTABLISHED
  TCP    [::1]:8080             [::1]:52649            ESTABLISHED
  TCP    [::1]:8080             [::1]:55770            ESTABLISHED
  TCP    [::1]:8080             [::1]:60271            ESTABLISHED
  TCP    [::1]:8080             [::1]:64833            ESTABLISHED
  TCP    [::1]:52533            [::1]:8080             ESTABLISHED
  TCP    [::1]:52649            [::1]:8080             ESTABLISHED
  TCP    [::1]:55770            [::1]:8080             ESTABLISHED
  TCP    [::1]:60271            [::1]:8080             ESTABLISHED
  TCP    [::1]:64833            [::1]:8080             ESTABLISHED

**Comment by FrostySo** [comment]
> its giving this now
> 
> C:\Users\Pratik>netstat -na | find "8080"
> TCP 0.0.0.0:8080 0.0.0.0:0 LISTENING
> TCP [::]:8080 [::]:0 LISTENING
> TCP [::1]:8080 [::1]:52533 ESTABLISHED
> TCP [::1]:8080 [::1]:52649 ESTABLISHED
> TCP [::1]:8080 [::1]:55770 ESTABLISHED
> TCP [::1]:8080 [::1]:60271 ESTABLISHED
> TCP [::1]:8080 [::1]:64833 ESTABLISHED
> TCP [::1]:52533 [::1]:8080 ESTABLISHED
> TCP [::1]:52649 [::1]:8080 ESTABLISHED
> TCP [::1]:55770 [::1]:8080 ESTABLISHED
> TCP [::1]:60271 [::1]:8080 ESTABLISHED
> TCP [::1]:64833 [::1]:8080 ESTABLISHED

Yea, it should detect that and change the port. I wonder if it's the port it changed to that doesn't seem to make it work. Don't know really. Will look into it later down the road. Not really an urgent matter, as you're the only one who's experienced this problem atm. But I still want to get it fixed

**Comment by pratikrao2195** [comment]
> > its giving this now
> > C:\Users\Pratik>netstat -na | find "8080"
> > TCP 0.0.0.0:8080 0.0.0.0:0 LISTENING
> > TCP [::]:8080 [::]:0 LISTENING
> > TCP [::1]:8080 [::1]:52533 ESTABLISHED
> > TCP [::1]:8080 [::1]:52649 ESTABLISHED
> > TCP [::1]:8080 [::1]:55770 ESTABLISHED
> > TCP [::1]:8080 [::1]:60271 ESTABLISHED
> > TCP [::1]:8080 [::1]:64833 ESTABLISHED
> > TCP [::1]:52533 [::1]:8080 ESTABLISHED
> > TCP [::1]:52649 [::1]:8080 ESTABLISHED
> > TCP [::1]:55770 [::1]:8080 ESTABLISHED
> > TCP [::1]:60271 [::1]:8080 ESTABLISHED
> > TCP [::1]:64833 [::1]:8080 ESTABLISHED
> 
> Yea, it should detect that and change the port. I wonder if it's the port it changed to that doesn't seem to make it work. Don't know really. Will look into it later down the road. Not really an urgent matter, as you're the only one who's experienced this problem atm. But I still want to get it fixed

Its totally issue of port number Today when I'm using pkg sender it again gave 500 i haven't change any configuration then i checked http-server using 8081 as default port then when i checked netstat then i found a tcp listening on 8080 so I've manually kill that process then again ran pkg sender then it worked for me.

so is pkg sender only work on 8080 or do i need to make some other configurations to allow it to use other ports without any error?

**Comment by FrostySo** [comment]
> > > its giving this now
> > > C:\Users\Pratik>netstat -na | find "8080"
> > > TCP 0.0.0.0:8080 0.0.0.0:0 LISTENING
> > > TCP [::]:8080 [::]:0 LISTENING
> > > TCP [::1]:8080 [::1]:52533 ESTABLISHED
> > > TCP [::1]:8080 [::1]:52649 ESTABLISHED
> > > TCP [::1]:8080 [::1]:55770 ESTABLISHED
> > > TCP [::1]:8080 [::1]:60271 ESTABLISHED
> > > TCP [::1]:8080 [::1]:64833 ESTABLISHED
> > > TCP [::1]:52533 [::1]:8080 ESTABLISHED
> > > TCP [::1]:52649 [::1]:8080 ESTABLISHED
> > > TCP [::1]:55770 [::1]:8080 ESTABLISHED
> > > TCP [::1]:60271 [::1]:8080 ESTABLISHED
> > > TCP [::1]:64833 [::1]:8080 ESTABLISHED
> > 
> > 
> > Yea, it should detect that and change the port. I wonder if it's the port it changed to that doesn't seem to make it work. Don't know really. Will look into it later down the road. Not really an urgent matter, as you're the only one who's experienced this problem atm. But I still want to get it fixed
> 
> Its totally issue of port number Today when I'm using pkg sender it again gave 500 i haven't change any configuration then i checked http-server using 8081 as default port then when i checked netstat then i found a tcp listening on 8080 so I've manually kill that process then again ran pkg sender then it worked for me.
> 
> so is pkg sender only work on 8080 or do i need to make some other configurations to allow it to use other ports without any error?

It is possible that it might work on port 8080 only. If you'd like, I can add an option to change the default port number that the program will try. Then you can see if it makes a difference or not.
