### ISSUE TITLE
Failed to initialize server - Address already in use

### ISSUE THREAD

**Issue by skrad9101** [FrostySo/Ps4-Pkg-Sender#17]
It is green and connected, but the status shows Failed to initialize server - Address already in use.

Not sure what kind of info should I provide.

![image](https://user-images.githubusercontent.com/55866949/123845800-35982180-d947-11eb-8149-3e2e7fa3283b.png)

**Comment by FrostySo** [comment]
Port 8080 is in use. You need to find what's using port 8080 and stop it. Then it will work.  If the program crashed randomly then go on task  manager and kill all "node" processes or even nodejs.

**Comment by skrad9101** [comment]
Thanks for the reply. I think I stopped what is using 8080, now it stuck on 0% and sending forever. What else should I do?

![image](https://user-images.githubusercontent.com/55866949/123990672-8e75c180-d9fc-11eb-8d37-400fd34ba7e6.png)
