### ISSUE TITLE
Additional_Content (DLC) is not installing

### ISSUE THREAD

**Issue by krugdenis** [FrostySo/Ps4-Pkg-Sender#2]
I know, Theme (Fake DLC Unlocker) files are not sending with RPI, but there is also Theme (Fake) versions of DLC, that's normally sends with basic RPI, but in your app that doesn't work

**Comment by FrostySo** [comment]
What does it show? 

I think this may be fixed in the next update for the reason I said in the latest reply on #1

**Comment by krugdenis** [comment]
Now it works

**Comment by yazer79** [comment]
I am still getting error 500 from server

**Comment by FrostySo** [comment]
> I am still getting error 500 from server
> V1.05 - win 10 home

Need more info on this. Pkg name etc
