### ISSUE TITLE
[Feedback] Improve/Update the App please

### ISSUE THREAD

**Issue by IRONB0SS** [FrostySo/Ps4-Pkg-Sender#21]
imagine adding hundreds of PKGs and all of a sudden RPI crashes, a feature to export install queue would be awesome
thanks for the efforts 💪

**Comment by FrostySo** [comment]
Added in https://github.com/FrostySo/Ps4-Pkg-Sender/commit/8816b19c7af4becea23fbfaf570c6507dc817b70

Let me know how it goes. 

I have not tested it on live environment so I wouldn't know how well it functions. But it should function the same.

Just replace the old exe (make a backup first). 

Ctrl + select items then right click -> export and to import just drag drop the json file into the sender or right click on an empty line. You can import multiple jsons at once too.

[Ps4-Pkg-Sender W Import-Export.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/10145375/Ps4-Pkg-Sender.W.Import-Export.zip)

**Comment by IRONB0SS** [comment]
> Added in [8816b19](https://github.com/FrostySo/Ps4-Pkg-Sender/commit/8816b19c7af4becea23fbfaf570c6507dc817b70)
> 
> Let me know how it goes.
> 
> I have not tested it on live environment so I wouldn't know how well it functions. But it should function the same.
> 
> Just replace the old exe (make a backup first).
> 
> Ctrl + select items then right click -> export and to import just drag drop the json file into the sender or right click on an empty line. You can import multiple jsons at once too.
> 
> [Ps4-Pkg-Sender W Import-Export.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/10145375/Ps4-Pkg-Sender.W.Import-Export.zip)

Doesn't Work, it exports the items to json but cannot import
no error no message why, it just doesn't add items

**Comment by FrostySo** [comment]
> > Added in [8816b19](https://github.com/FrostySo/Ps4-Pkg-Sender/commit/8816b19c7af4becea23fbfaf570c6507dc817b70)
> > Let me know how it goes.
> > I have not tested it on live environment so I wouldn't know how well it functions. But it should function the same.
> > Just replace the old exe (make a backup first).
> > Ctrl + select items then right click -> export and to import just drag drop the json file into the sender or right click on an empty line. You can import multiple jsons at once too.
> > [Ps4-Pkg-Sender W Import-Export.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/10145375/Ps4-Pkg-Sender.W.Import-Export.zip)
> 
> Doesn't Work, it exports the items to json but cannot import no error no message why, it just doesn't add items

Strange. I'm not sure what's wrong, here's it being done on my pc (the same exe I gave you) 

https://puu.sh/Jun7D/a501bf047e.mp4

I'll test it on other pc's and check

**Comment by IRONB0SS** [comment]
> > > Added in [8816b19](https://github.com/FrostySo/Ps4-Pkg-Sender/commit/8816b19c7af4becea23fbfaf570c6507dc817b70)
> > > Let me know how it goes.
> > > I have not tested it on live environment so I wouldn't know how well it functions. But it should function the same.
> > > Just replace the old exe (make a backup first).
> > > Ctrl + select items then right click -> export and to import just drag drop the json file into the sender or right click on an empty line. You can import multiple jsons at once too.
> > > [Ps4-Pkg-Sender W Import-Export.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/10145375/Ps4-Pkg-Sender.W.Import-Export.zip)
> > 
> > Doesn't Work, it exports the items to json but cannot import no error no message why, it just doesn't add items
> 
> Strange. I'm not sure what's wrong, here's it being done on my pc (the same exe I gave you) 
> 
> https://puu.sh/Jun7D/a501bf047e.mp4
> 
> I'll test it on other pc's and check
> 
> EDIT: wow yea some pcs it doesn't work. I'll try and fix this. Not sure what's wrong tbh. It shouldn't have this problem in theory
> 
> EDIT2: So I made it check to see if the file exists before importing, if it didn't it wouldn't. I've removed that check here temporarily just to see if it will work for you
> 
> [Ps4-Pkg-Sender W Import-Export.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/10252821/Ps4-Pkg-Sender.W.Import-Export.zip)
> 
> Try it here and let me know how it goes. Also, are you using a network drive? External drives are working fine for me but maybe if it's a network drive File.Exists might not work

Hey again, It imports files now but got this error

![20221220_113734.jpg](https://user-images.githubusercontent.com/97769328/208615629-c8f94740-3e74-4f3a-beaa-4f4cae165326.jpg)

**Comment by FrostySo** [comment]
> > > > Added in [8816b19](https://github.com/FrostySo/Ps4-Pkg-Sender/commit/8816b19c7af4becea23fbfaf570c6507dc817b70)
> > > > Let me know how it goes.
> > > > I have not tested it on live environment so I wouldn't know how well it functions. But it should function the same.
> > > > Just replace the old exe (make a backup first).
> > > > Ctrl + select items then right click -> export and to import just drag drop the json file into the sender or right click on an empty line. You can import multiple jsons at once too.
> > > > [Ps4-Pkg-Sender W Import-Export.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/10145375/Ps4-Pkg-Sender.W.Import-Export.zip)
> > > 
> > > 
> > > Doesn't Work, it exports the items to json but cannot import no error no message why, it just doesn't add items
> > 
> > 
> > Strange. I'm not sure what's wrong, here's it being done on my pc (the same exe I gave you)
> > https://puu.sh/Jun7D/a501bf047e.mp4
> > I'll test it on other pc's and check
> > EDIT: wow yea some pcs it doesn't work. I'll try and fix this. Not sure what's wrong tbh. It shouldn't have this problem in theory
> > EDIT2: So I made it check to see if the file exists before importing, if it didn't it wouldn't. I've removed that check here temporarily just to see if it will work for you
> > [Ps4-Pkg-Sender W Import-Export.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/10252821/Ps4-Pkg-Sender.W.Import-Export.zip)
> > Try it here and let me know how it goes. Also, are you using a network drive? External drives are working fine for me but maybe if it's a network drive File.Exists might not work
> 
> Hey again, It imports files now but got this error
> 
> ![20221220_113734.jpg](https://user-images.githubusercontent.com/97769328/208615629-c8f94740-3e74-4f3a-beaa-4f4cae165326.jpg)

Yea, are you using a network drive? That could explain why all these things are happening

**Comment by IRONB0SS** [comment]
> > > > > Added in [8816b19](https://github.com/FrostySo/Ps4-Pkg-Sender/commit/8816b19c7af4becea23fbfaf570c6507dc817b70)
> > > > > Let me know how it goes.
> > > > > I have not tested it on live environment so I wouldn't know how well it functions. But it should function the same.
> > > > > Just replace the old exe (make a backup first).
> > > > > Ctrl + select items then right click -> export and to import just drag drop the json file into the sender or right click on an empty line. You can import multiple jsons at once too.
> > > > > [Ps4-Pkg-Sender W Import-Export.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/10145375/Ps4-Pkg-Sender.W.Import-Export.zip)
> > > > 
> > > > 
> > > > Doesn't Work, it exports the items to json but cannot import no error no message why, it just doesn't add items
> > > 
> > > 
> > > Strange. I'm not sure what's wrong, here's it being done on my pc (the same exe I gave you)
> > > https://puu.sh/Jun7D/a501bf047e.mp4
> > > I'll test it on other pc's and check
> > > EDIT: wow yea some pcs it doesn't work. I'll try and fix this. Not sure what's wrong tbh. It shouldn't have this problem in theory
> > > EDIT2: So I made it check to see if the file exists before importing, if it didn't it wouldn't. I've removed that check here temporarily just to see if it will work for you
> > > [Ps4-Pkg-Sender W Import-Export.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/10252821/Ps4-Pkg-Sender.W.Import-Export.zip)
> > > Try it here and let me know how it goes. Also, are you using a network drive? External drives are working fine for me but maybe if it's a network drive File.Exists might not work
> > 
> > Hey again, It imports files now but got this error
> > 
> > ![20221220_113734.jpg](https://user-images.githubusercontent.com/97769328/208615629-c8f94740-3e74-4f3a-beaa-4f4cae165326.jpg)
> 
> Yea, are you using a network drive? That could explain why all these things are happening 

Yes, I have D-Link Gigabit Ethernet PCI and I connected PS4 to It with Lan Cable

**Comment by FrostySo** [comment]
> > > > > > Added in [8816b19](https://github.com/FrostySo/Ps4-Pkg-Sender/commit/8816b19c7af4becea23fbfaf570c6507dc817b70)
> > > > > > Let me know how it goes.
> > > > > > I have not tested it on live environment so I wouldn't know how well it functions. But it should function the same.
> > > > > > Just replace the old exe (make a backup first).
> > > > > > Ctrl + select items then right click -> export and to import just drag drop the json file into the sender or right click on an empty line. You can import multiple jsons at once too.
> > > > > > [Ps4-Pkg-Sender W Import-Export.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/10145375/Ps4-Pkg-Sender.W.Import-Export.zip)
> > > > > 
> > > > > 
> > > > > Doesn't Work, it exports the items to json but cannot import no error no message why, it just doesn't add items
> > > > 
> > > > 
> > > > Strange. I'm not sure what's wrong, here's it being done on my pc (the same exe I gave you)
> > > > https://puu.sh/Jun7D/a501bf047e.mp4
> > > > I'll test it on other pc's and check
> > > > EDIT: wow yea some pcs it doesn't work. I'll try and fix this. Not sure what's wrong tbh. It shouldn't have this problem in theory
> > > > EDIT2: So I made it check to see if the file exists before importing, if it didn't it wouldn't. I've removed that check here temporarily just to see if it will work for you
> > > > [Ps4-Pkg-Sender W Import-Export.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/10252821/Ps4-Pkg-Sender.W.Import-Export.zip)
> > > > Try it here and let me know how it goes. Also, are you using a network drive? External drives are working fine for me but maybe if it's a network drive File.Exists might not work
> > > 
> > > 
> > > Hey again, It imports files now but got this error
> > > ![20221220_113734.jpg](https://user-images.githubusercontent.com/97769328/208615629-c8f94740-3e74-4f3a-beaa-4f4cae165326.jpg)
> > 
> > 
> > Yea, are you using a network drive? That could explain why all these things are happening
> 
> Yes, I have D-Link Gigabit Ethernet PCI and I connected PS4 to It with Lan Cable

So the files you are trying to send are in a network drive? Such as, over from another server? If you network share the drives it just doesn't work because when you are accessing a folder over the network, it is queried in real time to display the data. You'd need to copy those files over to a physical drive on your computer. 

The reason why importing worked now is that I got rid of the File.Exists function which essentially checks if the file is physically there or not. That is why it is failing. 

[Ps4-Pkg-Sender W Import-Export.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/10273726/Ps4-Pkg-Sender.W.Import-Export.zip)

This version here skips them automatically and displays a message. You will see what I mean if you use it.

**Comment by IRONB0SS** [comment]
> > > > > > > Added in [8816b19](https://github.com/FrostySo/Ps4-Pkg-Sender/commit/8816b19c7af4becea23fbfaf570c6507dc817b70)
> > > > > > > Let me know how it goes.
> > > > > > > I have not tested it on live environment so I wouldn't know how well it functions. But it should function the same.
> > > > > > > Just replace the old exe (make a backup first).
> > > > > > > Ctrl + select items then right click -> export and to import just drag drop the json file into the sender or right click on an empty line. You can import multiple jsons at once too.
> > > > > > > [Ps4-Pkg-Sender W Import-Export.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/10145375/Ps4-Pkg-Sender.W.Import-Export.zip)
> > > > > > 
> > > > > > 
> > > > > > Doesn't Work, it exports the items to json but cannot import no error no message why, it just doesn't add items
> > > > > 
> > > > > 
> > > > > Strange. I'm not sure what's wrong, here's it being done on my pc (the same exe I gave you)
> > > > > https://puu.sh/Jun7D/a501bf047e.mp4
> > > > > I'll test it on other pc's and check
> > > > > EDIT: wow yea some pcs it doesn't work. I'll try and fix this. Not sure what's wrong tbh. It shouldn't have this problem in theory
> > > > > EDIT2: So I made it check to see if the file exists before importing, if it didn't it wouldn't. I've removed that check here temporarily just to see if it will work for you
> > > > > [Ps4-Pkg-Sender W Import-Export.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/10252821/Ps4-Pkg-Sender.W.Import-Export.zip)
> > > > > Try it here and let me know how it goes. Also, are you using a network drive? External drives are working fine for me but maybe if it's a network drive File.Exists might not work
> > > > 
> > > > 
> > > > Hey again, It imports files now but got this error
> > > > ![20221220_113734.jpg](https://user-images.githubusercontent.com/97769328/208615629-c8f94740-3e74-4f3a-beaa-4f4cae165326.jpg)
> > > 
> > > 
> > > Yea, are you using a network drive? That could explain why all these things are happening
> > 
> > Yes, I have D-Link Gigabit Ethernet PCI and I connected PS4 to It with Lan Cable
> 
> So the files you are trying to send are in a network drive? Such as, over from another server? If you network share the drives it just doesn't work because when you are accessing a folder over the network, it is queried in real time to display the data. You'd need to copy those files over to a physical drive on your computer. 
> 
> The reason why importing worked now is that I got rid of the File.Exists function which essentially checks if the file is physically there or not. That is why it is failing. 
> 
> [Ps4-Pkg-Sender W Import-Export.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/10273726/Ps4-Pkg-Sender.W.Import-Export.zip)
> 
> This version here skips them automatically and displays a message. You will see what I mean if you use it. 
> 

I didn't understand correctly before, Yes I have physical HDD 4TB, I will test in report back ASAP, Thanks

**Comment by FrostySo** [comment]
> 

Need to be more specific than just "doesn't work". I've tested it on my laptop and my pc, both worked just fine.

**Comment by IRONB0SS** [comment]
> > 
> 
Below Error Happens, I can Import game without problem before RPI Crashes
I assume pkg file names is the reason
For example I renamed RE3 file to "Resident Evil 3", so when I try to send the pkg to PS4, the app rename the name to "ResidentEvil3" and I think existing Space between words is the problem, I will test and report back

![Screenshot 2023-01-02 123506](https://user-images.githubusercontent.com/97769328/210212764-095df5a5-d1d5-4435-a2a7-d4a40a8dc257.jpg)

**Comment by IRONB0SS** [comment]
> > 
> 
> Need to be more specific than just "doesn't work". I've tested it on my laptop and my pc, both worked just fine. 

Hey again my friend, thanks for the efforts ❤️🙏

Import/export works like charm 

Note* when you have space in the name of the PKG, sender app won't import the file ( it's okay no need to work on this)

Again, thanks a lot for your time and patience 🙏

Best regards

**Comment by FrostySo** [comment]
> Note* when you have space in the name of the PKG, sender app won't import the file ( it's okay no need to work on this)

Will take a look and see if it's an easy fix. If it is, may as well just fix it lol

Thanks for the feedback though
