### ISSUE TITLE
failed - remote PKG installer has crashed. Please restart it on your PS4

### ISSUE THREAD

**Issue by Constantine-HD** [FrostySo/Ps4-Pkg-Sender#4]
today i have new problem ... when i add multi game and start transferring to ps4 after 80% of transferring first file get this error for all files but the first game on the list continued to transferring until the end and then stop

error in status is : failed - remote PKG installer has crashed. Please restart it on your PS4

i test with another pkg sender to make shure that remote installer in ps4 haven't problem...there was no error with them

**Comment by FrostySo** [comment]
Change the timeout delay from whatever value you have it on to 5-10 seconds more than before. 

You can do that by changing ProgressCheckDelay in settings.json

Keep changing it till the error stops. This error is an issue with the remote pkg installer itself. 

It cannot be fixed properly without changing the code within the pkg installer itself, which I explained in a tweet of mine why that's a bad idea.
