### ISSUE TITLE
problem feedback 

### ISSUE THREAD

**Issue by Constantine-HD** [FrostySo/Ps4-Pkg-Sender#5]
hi ...i use Ps4 Pkg Sender V1.04 for transfer pkg to 3 console in same time...start transfer to console 1 and everything is ok ..open second Ps4 Pkg Sender and set console 2 ip and start  transferring but console 1 stop to  transferring

i think auto port selector not work properly

**Comment by FrostySo** [comment]
Oh no that's not auto ip port. 

On each server start, it kills all node.exe processes to ensure ports are free. So this is why it would do that. Feel free to compile it yourself and remove that.
