### ISSUE TITLE
Cannot handle special characters

### ISSUE THREAD

**Issue by dlxmax** [FrostySo/Ps4-Pkg-Sender#9]
Typically, if both the filename and the "title" have a ® or ™, the send fails with HTTP error 500.
My workaround is to remove the character from the filename.

**Comment by FrostySo** [comment]
> Typically, if both the filename and the "title" have a ® or ™, the send fails with HTTP error 500.
> My workaround is to remove the character from the filename.

Interesting. I didn't think they'd have such titles. That might actually explain why spiderman fails to install through it. Could you try rename the filename yourself and let me know if it works? I think RPI itself does not handle special characters, which causes the socket to eventually kill itself after a certain amount of bytes are sent over.

I can make it handle the special characters, but only if it works after renaming them. No point in doing that, if RPI itself stealth crashes while installing.

**Comment by dlxmax** [comment]
Yes, removing the special characters from the file name results in a good send.
I've done this many times with different fpkgs.

**Comment by FrostySo** [comment]
> Yes, removing the special characters from the file name results in a good send.
> I've done this many times with different fpkgs.

Ok, thanks!

I'll fix it sometime this week. When I get some free time to 😊

**Comment by FrostySo** [comment]
Just an update; I'm 80% done. Currently reworking a few things because I unpleasant with it. 

So it might take a bit longer. 

But when it's done, it will rename file on queue and rename it back after. This is for those people who like the naming to stay consistent (for ordering sake).

Hopefully it'll be done sometime within the next few days. But I am a bit busy, so no guarantees.

**Comment by FrostySo** [comment]
Hi again. 

I know it's been a while. I've been a bit busy. It is finally finished though. 

Please do note this though. File renaming is not supported with network drives. So you will have to manually rename them if it fails. It will tell you if it fails.

[Release.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/6177125/Release.zip)

**Comment by FrostySo** [comment]
@dlxmax  I will be closing this now. You can either re-open this or make a new issue if any other issues persist.
